app/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.fields.html5 import DateField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired, Email, Length


class ProfileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=25)])
    phone = StringField('Phone', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    bio = TextAreaField('Bio', validators=[Length(max=250)])
    address = StringField('Address', validators=[DataRequired(), Length(max=150)])
    # avatar = FileField()
    submit = SubmitField('Done')


class PaymentForm(FlaskForm):
    card_number = StringField('Card number', validators=[DataRequired(), Length(min=14, max=14)])
    card_owner_name = StringField('Name', validators=[DataRequired(), Length(min=3, max=100)])
    start_date = DateField('Start date', validators=[DataRequired()], format='%Y-%m-%d')
    end_date = DateField('End date', validators=[DataRequired()], format='%Y-%m-%d')
    cvc = StringField('CVC', validators=[DataRequired(), Length(min=3, max=3)])
    submit = SubmitField('Save')

app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from app.profile import routes, forms

app/profile/routes.py
from datetime import datetime
import requests
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
from app import db
from app.profile import bp
from .forms import ProfileForm, PaymentForm
from ..models import Payment, Avatar, User


@bp.route('/profile')
@login_required
def profile():
    payment = Payment.query.filter_by(user_id=current_user.id).first()
    return render_template('profile/profile.html', title='Profile', user=current_user, payment=payment)


@bp.route('/profile/info/edit', methods=['GET', 'POST'])
@login_required
def edit_profile_info():
    form = ProfileForm()

    payment = Payment.query.filter_by(user_id=current_user.id).first()

    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash('Email has already in use by another account.')
            return redirect(url_for('profile.profile'))
        current_user.name = form.name.data
        current_user.phone = form.phone.data
        current_user.address = form.address.data
        current_user.bio = form.bio.data
        if current_user.email != form.email.data:
            current_user.email_activated = False
        current_user.email = form.email.data
        db.session.commit()
        flash('Your changes has been made.')
        return redirect(url_for('profile.profile'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.phone.data = current_user.phone
        form.email.data = current_user.email
        form.address.data = current_user.address
        form.bio.data = current_user.bio
    return render_template('profile/edit_profile.html', title='Edit Profile', form=form, user=current_user, payment=payment)


@bp.route('/profile/payment/edit')
def edit_profile_payment():
    form = PaymentForm()

    payment_data_from_db = Payment.query.filter_by(user_id=current_user.id).first()
    url = current_app.config['PAYMENT_SERVICE_URL'] + '/api/cards/info'
    headers = {'X-Credentials': str(payment_data_from_db.credentials)}

    payment = requests.get(
        url=url,
        headers=headers
    ).json()
    
    if request.method == 'GET':
        form.card_number.data = payment['card_number']
        form.card_owner_name.data = payment['name']
        form.start_date.data = datetime.strptime(payment['start_date'], '%Y-%m-%d')
        form.end_date.data = datetime.strptime(payment['end_date'], '%Y-%m-%d')
        form.cvc.data = payment['cvc']
    return render_template('profile/edit_payment.html', title='Edit Payment', form=form, user=current_user, payment=payment)


@bp.route('/profile/payment/delete')
def delete_profile_payment():
    payment = Payment.query.filter_by(user_id=current_user.id).first()
    db.session.delete(payment)
    db.session.commit()
    flash('Your payment has been deleted.')
    return redirect(url_for('profile.profile'))


@bp.route('/profile/payment/new', methods=['GET', 'POST'])
def new_profile_payment():
    form = PaymentForm()
    url = current_app.config['PAYMENT_SERVICE_URL'] + '/api/cards/validate'
    if form.validate_on_submit():
        req = requests.post(
            url=url,
            json={
                'card_number': form.card_number.data,
                'name': form.card_owner_name.data,
                'start_date': form.start_date.data.strftime('%Y-%m-%d'),
                'end_date': form.end_date.data.strftime('%Y-%m-%d'),
                'cvc': form.cvc.data
            }
        )
        if (req.status_code == 200):
            new_payment = Payment(card_number=form.card_number.data, credentials=req.text, user_id=current_user.id)
            db.session.add(new_payment)
            db.session.commit()
            flash('Your new payment has been created.')
        elif (req.status_code == 400 or req.status_code == 401):
            flash('You have input wrong infomation, please check again.')
        elif (req.status_code == 404):
            return render_template('404.html')

        return redirect(url_for('profile.profile'))
    return render_template('profile/new_payment.html', title='New Payment', form=form, user=current_user, payment=None)

app/templates/profile/edit_payment.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/profile/edit_payment.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <section id="base-info">
        <div class="row">
            <div class="col-auto">
                <img class="profile-image" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="profile image">
            </div>
            <div class="col">
                <h2>{{ user.username }}</h2>
                <p>{{ user.phone }}</p>
                <p>
                    {{ user.email }}
                    {% if user.email_activated %}
                        <span class="text-success">(verified <i class="fas fa-check"></i>)</span>
                    {% else %}
                        <span class="text-muted">(not verified) <a class="text-info" href="{{ url_for('auth.verify_email_request') }}">verify?</a></span>
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="mt-3">
            <h2>Bio</h2>
            <p>{{ user.bio }}</p>
        </div>
    </section>
    <hr>
    <section id="address">
        <h2>Address</h2>
        <div class="row">
            <!-- <div class="col"></div> -->
            <div class="col">
                {{ user.address }}
            </div>
        </div>
    </section>
    <hr>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <section id="payment">
            <h2>Payment</h2>
            <div class="row">
                <div class="card col-6 mt-3 ml-3 mb-5">
                    <div class="card-body">
                        {{ form.card_number.label(class='label') }}
                        {{ form.card_number(value=payment.card_number, placeholder="Card number", class='payment-input') }}
                        <i class="fab fa-cc-visa payment-icon"></i>
                    </div>
                    <div class="card-body">
                        {{ form.card_owner_name.label(class='label') }}
                        {{ form.card_owner_name(value=payment.name, placeholder="Name", class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.start_date.label(class='label') }}
                        {{ form.start_date(value=payment.start_date, class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.end_date.label(class='label') }}
                        {{ form.end_date(value=payment.end_date, class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.cvc.label(class='label') }}
                        {{ form.cvc(size=5, value=payment.cvc, placeholder='CVC') }}
                    </div>
                </div>
            </div>
        </section>
    </form>

    <section id="confirm">
        <button class="button">
            <a href="{{ url_for('profile.profile') }}" class="link">Discard</a>
        </button>
        <button type="button" class="button" data-toggle="modal" data-target="#deleteModal">
            <div class="link">Delete</div>
        </button>
    </section>

    <section id="modal">
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Do you really want to remove your payment?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="button" data-dismiss="modal">
                            <div class="link">Close</div>
                        </button>
                        <button type="button" class="button">
                            <a href="{{ url_for('profile.delete_profile_payment') }}" class="link">Delete</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/profile/edit_profile.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/profile/edit_profile.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <section id="base-info">
            <div class="row">
                <div class="col-auto">
                    <img class="profile-image" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="profile image">
                </div>
                <div class="col">
                    <div class="input-container">
                        {{ form.name.label(class='label') }}
                        {{ form.name(value=user.name, placeholder="Name", class='input-text') }}
                    </div>
                    <div class="input-container">
                        {{ form.phone.label(class='label') }}
                        {{ form.phone(value=user.phone, placeholder="Phone", class='input-text') }}
                    </div>
                    <div class="input-container">
                        {{ form.email.label(class='label') }}
                        {{ form.email(value=user.email, placeholder="Email", class='input-text') }}
                    </div>
                </div>
            </div>
            <div class="mt-3">
                <h2>{{ form.bio.label }}</h2>
                <textarea name="bio" id="bio" cols="30" rows="10">{{ user.bio }}</textarea>
                <!-- {{ form.bio(cols=30, rows=10) }} -->
            </div>
        </section>
        <hr>
        <section id="address">
            <h2>{{ form.address.label }}</h2>
            <div class="row">
                <!-- <div class="col"></div> -->
                <div class="col">
                    <div class="input-container">
                        {{ form.address(value=user.address, placeholder="Address", class='input-text') }}
                    </div>
                </div>
            </div>
        </section>
        <hr>
        <section id="payment">
            <h2>Payment</h2>
            {% if payment %}
                <div class="row">
                    <div class="card mt-3 ml-3">
                        <div class="card-body">
                            {{ payment.card_number }}
                            <i class="fab fa-cc-visa payment-icon"></i>
                        </div>
                    </div>
                </div>
            {% endif %}
        </section>
    
        <section id="confirm">
            <button class="button">
                <a href="{{ url_for('profile.profile') }}" class="link">Discard</a>
            </button>
            <button class="button" type="submit">
                {{ form.submit(class='input-submit') }}
            </button>
        </section>
    </form>
{% endblock %}

app/templates/profile/new_payment.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/profile/new_payment.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <section id="base-info">
        <div class="row">
            <div class="col-auto">
                <img class="profile-image" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="profile image">
            </div>
            <div class="col">
                <h2>{{ user.username }}</h2>
                <p>{{ user.phone }}</p>
                <p>
                    {{ user.email }}
                    {% if user.email_activated %}
                        <span class="text-success">(verified <i class="fas fa-check"></i>)</span>
                    {% else %}
                        <span class="text-muted">(not verified) <a class="text-info" href="{{ url_for('auth.verify_email_request') }}">verify?</a></span>
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="mt-3">
            <h2>Bio</h2>
            <p>{{ user.bio }}</p>
        </div>
    </section>
    <hr>
    <section id="address">
        <h2>Address</h2>
        <div class="row">
            <!-- <div class="col"></div> -->
            <div class="col">
                {{ user.address }}
            </div>
        </div>
    </section>
    <hr>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <section id="payment">
            <h2>Payment</h2>
            <div class="row">
                <div class="card col-6 mt-3 ml-3 mb-5">
                    <div class="card-body">
                        {{ form.card_number.label(class='label') }}
                        {{ form.card_number(value=payment.card_number, placeholder="Card number", class='payment-input') }}
                        <i class="fab fa-cc-visa payment-icon"></i>
                    </div>
                    <div class="card-body">
                        {{ form.card_owner_name.label(class='label') }}
                        {{ form.card_owner_name(value=payment.name, placeholder="Name", class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.start_date.label(class='label') }}
                        {{ form.start_date(value=payment.start_date, class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.end_date.label(class='label') }}
                        {{ form.end_date(value=payment.end_date, class='payment-input') }}
                    </div>
                    <div class="card-body">
                        {{ form.cvc.label(class='label') }}
                        {{ form.cvc(size=5, value=payment.cvc, placeholder='CVC') }}
                    </div>
                </div>
            </div>
        </section>

        <section id="confirm">
            <button class="button">
                <a href="{{ url_for('profile.profile') }}" class="link">Discard</a>
            </button>
            <button class="button" type="submit">
                {{ form.submit(class='input-submit') }}
            </button>
        </section>
    </form>
{% endblock %}

app/templates/profile/profile.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/profile/profile.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <section id="base-info">
        <div class="row">
            <div class="col-auto">
                <img class="profile-image" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="profile image">
            </div>
            <div class="col">
                <h2>{{ user.name }}</h2>
                <p>{{ user.phone }}</p>
                <p>
                    {{ user.email }}
                    {% if user.email_activated %}
                        <span class="text-success">(verified <i class="fas fa-check"></i>)</span>
                    {% else %}
                        <span class="text-muted">(not verified) <a class="text-info" href="{{ url_for('auth.verify_email_request') }}">verify?</a></span>
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="mt-3">
            <h2>Bio</h2>
            <p>{{ user.bio }}</p>
        </div>
    </section>
    <hr>
    <section id="address">
        <h2>Address</h2>
        <div class="row">
            <!-- <div class="col"></div> -->
            <div class="col">
                {{ user.address }}
            </div>
        </div>
    </section>
    <hr>
    <section id="payment">
        <div class="custom-row">
            <h2>Payment</h2>
            <div class="ml-1 col-1">
                <button class="create-button">
                    {% if not payment %}
                        <a href="{{ url_for('profile.new_profile_payment') }}" class="create-link"><i class="fas fa-plus"></i></a>
                    {% else %}
                        <a href="#" class="create-link"><i class="fas fa-plus"></i></a>
                    {% endif %}
                </button>
            </div>
        </div>
        {% if payment %}
            <div class="row">
                <div class="card mt-3 ml-3">
                    <div class="card-body">
                        <a class="card-number-link" href="{{ url_for('profile.edit_profile_payment') }}">{{ payment.card_number }}</a>
                        <i class="fab fa-cc-visa payment-icon"></i>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>

    <section id="edit">
        <button class="edit-button">
            <a href="{{ url_for('profile.edit_profile_info') }}" class="edit-link">Edit</a>
        </button>
    </section>
{% endblock %}