app/orders/__init__.py
from flask import Blueprint

bp = Blueprint('orders', __name__)

from app.orders import routes

app/orders/routes.py
from app.models import Product
import requests
from flask import render_template, current_app, url_for
from flask_login import current_user
from app.orders import bp


@bp.route('/orders')
def orders():
    token = current_user.get_seller_token()
    url = current_app.config['SHIPPING_SERVICE_URL'] + '/api/orders'
    req = requests.get(
        url=url,
        headers={
            'Content-Type': 'application/json',
            'X-Auth-Token': token
        }
    )

    data = req.json()

    orders = data['orders']
    prev_url = url_for('orders.orders', page=data['_meta']['prevPage']) if data['_meta']['prevPage'] else None
    next_url = url_for('orders.orders', page=data['_meta']['nextPage']) if data['_meta']['nextPage'] else None

    return render_template('orders/orders.html', orders=orders, prev_url=prev_url, next_url=next_url)


@bp.route('/orders/<id>')
def orders_details(id):
    token = current_user.get_seller_token()
    url = current_app.config['SHIPPING_SERVICE_URL'] + '/api/orders/' + id
    image_service_url = current_app.config['IMAGE_SERVICE_URL'] + '/images/'
    req = requests.get(
        url=url,
        headers={
            'Content-Type': 'application/json',
            'X-Auth-Token': token
        }
    )

    order = req.json()
    product = Product.query.filter_by(id=order['productId']).first()

    return render_template('orders/orders_details.html', order=order, image_service_url=image_service_url, product=product.get_product_info())

app/templates/orders/orders.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <!-- <section class="search mt-4">
            <div class="search-form col-8 col-12 col-md-6">
                <form class="">
                    <input class="form-control mr-sm-2 input-searchbar" type="search" placeholder="Search for an order" aria-label="Search">
                </form>
            </div>
        </section> -->

        <section class="orders mt-4">
            {% for order in orders %}
                <div class="col-12 col-md-7 col-lg-6 mt-3">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{ url_for('orders.orders_details', id=order._id) }}">Order {{ order._id }}</a>
                            </h4>
                            <p class="card-text">
                                {{ order.createdAt }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <br>

            <div class="col-12 mt-5">
                <nav aria-label="...">
                    <ul class="pagination">
                        {% if prev_url %}
                            <li class="page-item">
                                <a class="page-link" href="{{ prev_url }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="{{ prev_url }}">Previous</a>
                            </li>
                        {% endif %}

                        {% if next_url %}
                            <li class="page-item">
                                <a class="page-link" href="{{ next_url }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="{{ next_url }}">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </section>
    </div>
{% endblock %}

app/templates/orders/orders_details.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/orders/orders_details.css') }}" rel="stylesheet" />
{% endblock %}

{% block external_links %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
{% endblock %}

{% block content %}
    <div class="container">
        <section class="title">
            <h2>Order {{ order._id }}</h2>
            <p>{{ order.createdAt }}</p>
        </section>
        
        <hr>

        <section class="product-info">
            <h2>Products</h2>
            <div class="row justify-content-center align-items-center">
                <div class="col-12 mt-2">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <p class="card-text">
                                    <img class="product-image ml-2 mr-4" src="{{ [image_service_url, product.pictures[0].img_id]|join('') }}" alt="Product's image">
                                    <div class="">
                                        <p>Name: {{ product.name }}</p>
                                        <p>Price: {{ "{:,}".format((product.price * 1000)|int) }} đ</p>
                                        <p>Quantity: {{ order.quantity }}</p>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <hr>

        <section class="address-info">
            <h2>Deliver to</h2>
            <p>{{ order.deliverTo }}</p>
        </section>

        <hr>

        <section class="progress-info">
            <h2>Progress</h2>
            <div class="card1 mt-4">
                <ul id="progressbar" class="text-center">
                    <li class="active step0"></li>

                    {% if order.hasTaken %}
                        <li class="active step0"></li>
                    {% else %}
                        <li class="step0"></li>
                    {% endif %}

                    {% if order.isDelivering %}
                        <li class="active step0"></li>
                    {% else %}
                        <li class="step0"></li>
                    {% endif %}

                    {% if order.isDelivered %}
                        <li class="active step0"></li>
                    {% else %}
                        <li class="step0"></li>
                    {% endif %}
                </ul>
                <h6 class="mb-5">Bagging the product</h6>
                <h6 class="mb-5">Tallie has taken the package</h6>
                <h6 class="mb-5">Tallie is delivering the package</h6>
                <h6 class="mb-5">The package has been delivered to you</h6>
            </div>
        </section>
    </div>
{% endblock %}