app/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField, FloatField, SubmitField, MultipleFileField, SelectField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired, Length


class ProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=5, max=100)])
    author = StringField('Author', validators=[DataRequired(), Length(min=3, max=100)])
    price = FloatField(validators=[DataRequired()])
    quantity = IntegerField(validators=[DataRequired()])
    description = TextAreaField(validators=[DataRequired(), Length(max=2000)])
    category = SelectField('Category', validators=[DataRequired()], choices=[])
    images = MultipleFileField()
    submit = SubmitField('Save')


class SearchForm(FlaskForm):
    q = StringField('Search', validators=[DataRequired()])

app/products/__init__.py
from flask import Blueprint

bp = Blueprint('products', __name__)

from app.products import routes, forms

app/products/routes.py
import requests
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
from sqlalchemy import or_
from app import db
from app.products import bp
from .forms import ProductForm, SearchForm
from ..models import Category, User, Product, Review, Picture


@bp.route('/your_product')
@login_required
def your_product():
    form = SearchForm()
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter_by(seller_id=current_user.id).paginate(
        page, current_app.config['PRODUCTS_PER_PAGE'], False
    )
    image_service_url = current_app.config['IMAGE_SERVICE_URL'] + '/images/'
    pictures = []
    for product in products.items:
        pic = Picture.query.filter_by(product_id = product.id).first()
        if pic is not None:
            pictures.append(pic.img_id)
        else:
            pictures.append(-1)

    next_url = url_for('products.your_product', page=products.next_num) if products.has_next else None
    prev_url = url_for('products.your_product', page=products.prev_num) if products.has_prev else None
    return render_template('products/products.html', title='Home', products=products, form=form, image_service_url=image_service_url, pictures=pictures, next_url=next_url, prev_url=prev_url)


@bp.route('/your_product/<id>')
@login_required
def your_product_details(id):
    product = Product.query.filter_by(id=id).first()
    reviews_users = db.session.query(Review, User).filter(Review.product_id==product.id).join(User, Review.user_id==User.id)
    pictures = Picture.query.filter_by(product_id=product.id).all()
    image_service_url = current_app.config['IMAGE_SERVICE_URL'] + '/images/'
    return render_template('products/product_details.html', product=product, reviews=reviews_users, pictures=pictures, image_service_url=image_service_url)


@bp.route('/your_product/<id>/delete')
@login_required
def your_product_delete(id):
    product = Product.query.filter_by(id=id).first()
    reviews = Review.query.filter_by(product_id=product.id).all()
    pictures = Picture.query.filter_by(product_id=product.id).all()
    db.session.delete(product)
    if reviews:
        for review in reviews:
            db.session.delete(review)
        db.session.commit()
    if pictures:
        for pic in pictures:
            url = current_app.config['IMAGE_SERVICE_URL'] + f'/images/{pic.img_id}/delete'
            req = requests.delete(
                url=url
            )
            db.session.delete(pic)
    db.session.commit()
    flash(f'Your product: {product.name} has been deleted!')
    return redirect(url_for('products.your_product'))


@bp.route('/your_product/new', methods=['GET', 'POST'])
@login_required
def your_product_new():
    form = ProductForm()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    url =  current_app.config['IMAGE_SERVICE_URL'] + '/upload_multiple'
    headers = {}
    payload = {}

    if request.method == 'POST' and form.validate_on_submit():
        category = Category.query.filter_by(id=form.category.data).first()
        if request.files['images'].filename != '':
            files = []
            for file in form.images.data:
                files.append(('pic', (file.filename, file.stream.read(), file.mimetype)))

            req = requests.post(
                url=url,
                headers=headers,
                data=payload,
                files=files
            ).json()

        product = Product(
            name=form.name.data, 
            author=form.author.data, 
            price=form.price.data / 1000, 
            quantity=form.quantity.data, 
            description=form.description.data,
            seller_id=current_user.id
        )
        product.categories.append(category)
        db.session.add(product)
        db.session.commit()

        if request.files['images'].filename != '':
            pictures = []
            for pic in req['data']:
                pictures.append(Picture(img_id=pic['id'], product_id=product.id))
            product.pictures = pictures
        db.session.add(product)
        db.session.commit()
        flash('Your product has been added!')
        return redirect(url_for('products.your_product'))
    return render_template('products/new_product.html', form=form)


@bp.route('/your_product/<id>/edit', methods=['GET', 'POST'])
@login_required
def your_product_edit(id):
    form = ProductForm()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    product = Product.query.filter_by(id=id).first()
    product_category = product.get_category()
    categories = Category.query.all()

    upload_url =  current_app.config['IMAGE_SERVICE_URL'] + '/upload_multiple'
    headers = {}
    payload = {}

    image_service_url = current_app.config['IMAGE_SERVICE_URL'] + '/images/'
    pictures = []
    pictures_from_db = Picture.query.filter_by(product_id=product.id).all()
    for pic in pictures_from_db:
        pictures.append(pic.img_id)

    if form.validate_on_submit():
        category = Category.query.filter_by(id=form.category.data).first()
        if request.files['images'].filename != '':
            files = []
            for file in form.images.data:
                files.append(('pic', (file.filename, file.stream.read(), file.mimetype)))
                print(f'Filename = {file.filename}')
                print(f'Mimetype = {file.mimetype}')

            req = requests.post(
                url=upload_url,
                headers=headers,
                data=payload,
                files=files
            ).json()

            for pic in req['data']:
                product.pictures.append(Picture(img_id=pic['id'], product_id=product.id))

        product.name = form.name.data
        product.author = form.author.data
        product.price = form.price.data / 1000
        product.quantity = form.quantity.data
        product.description = form.description.data
        if product_category != category:
            product.set_category(category)
        db.session.add(product)
        db.session.commit()
        flash('Your changes has been made.')
        return redirect(url_for('products.your_product', id=id))
    elif request.method == 'GET':
        form.name.data = product.name
        form.author.data = product.author
        form.price.data = product.price
        form.quantity.data = product.quantity
        form.description.data = product.description
    return render_template('products/edit_product.html', form=form, product=product, image_service_url=image_service_url, pictures=pictures, categories=categories, product_category=product_category)


@bp.route('/your_product/pictures/<id>/delete')
def delete_product_picture(id):
    pic = Picture.query.filter_by(img_id=id).first()
    product = Product.query.filter_by(id=pic.product_id).first()

    url = current_app.config['IMAGE_SERVICE_URL'] + f'/images/{pic.img_id}/delete'
    req = requests.delete(
        url=url
    )
    if req.status_code == 404:
        flash('Delete failed, image not found in image database.')
        return redirect(url_for('products.your_product_edit', id=product.id))
    product.pictures.remove(pic)
    db.session.add(product)
    db.session.delete(pic)
    db.session.commit()
    flash('Image deleted.')
    return redirect(url_for('products.your_product_edit', id=product.id))


@bp.route('/your_product/search', methods=['POST'])
def search_products():
    query = request.form['search']
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter(or_(Product.name.ilike(f'%{query}%'), Product.author.ilike(f'%{query}%'))).paginate(
        page, current_app.config['PRODUCTS_PER_PAGE'], False
    )
    image_service_url = current_app.config['IMAGE_SERVICE_URL'] + '/images/'
    pictures = []
    for product in products.items:
        pic = Picture.query.filter_by(product_id = product.id).first()
        if pic is not None:
            pictures.append(pic.img_id)
        else:
            pictures.append(-1)

    next_url = url_for('products.search_products', page=products.next_num) if products.has_next else None
    prev_url = url_for('products.search_products', page=products.prev_num) if products.has_prev else None
    return render_template('products/search_products.html', title='Search', products=products, image_service_url=image_service_url, pictures=pictures, next_url=next_url, prev_url=prev_url)

app/templates/products/edit_product.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/products/edit_product.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <form method="POST" action="{{ url_for('products.your_product_edit', id=product.id) }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <section id="images">
            {% for picture in pictures %}
                <div class="picture-wrapper">
                    <img class="product-picture" src="{{ [image_service_url, picture]|join('') }}" alt="">
                    <a href="{{ url_for('products.delete_product_picture', id=picture) }}" class="picture-delete"></a>
                </div>
            {% endfor %}
            <label class="image-upload ml-2">
                {{ form.images() }}
                <div class="image-upload-symbol"><i class="fas fa-plus"></i></div>
            </label>
        </section>

        <section id="base-info">
            <div class="input-container">
                {{ form.name.label(class='label') }}
                {{ form.name(value=product.name, placeholder="Name", class="input-text") }}
            </div>
            <div class="input-container">
                {{ form.author.label(class='label') }}
                {{ form.author(placeholder="Author", class="input-text") }}
            </div>
            <div class="input-container">
                {{ form.price.label(class='label') }}
                {{ form.price(value=product.price * 1000, placeholder="Price", class="input-number", type="number") }}
                VND
            </div>
            <div class="input-container">
                {{ form.quantity.label(class='label') }}
                {{ form.quantity(value=product.quantity, placeholder="Quantity", class="input-number", type="number") }}
            </div>
            <div class="input-container">
                <label for="category" class="label">Category</label>
                <select name="category" id="category" class="input-text">
                    {% for category in categories %}
                        {% if category.id == product_category.id %}
                            <option selected value="{{ category.id }}">{{ category.name }}</option>
                        {% else %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div>
                <h3>{{ form.description.label }}</h3>
                <textarea name="description" id="description" cols="30" rows="10">{{ product.description }}</textarea>
            </div>
        </section>
    
        <section id="confirm">
            <button class="button">
                <a href="{{ url_for('products.your_product_details', id=product.id) }}" class="link">Discard</a>
            </button>
            <button class="button" type="submit">
                {{ form.submit(class='input-submit') }}
            </button>
        </section>
    </form>
{% endblock %}

app/templates/products/new_product.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/products/edit_product.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <form method="POST" action="{{ url_for('products.your_product_new') }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <section id="image-section">
            <label class="image-upload ml-2">
                {{ form.images() }}
                <div class="image-upload-symbol"><i class="fas fa-plus"></i></div>
            </label>
        </section>

        <section id="base-info">
            <div class="input-container">
                {{ form.name.label() }}:
                {{ form.name(placeholder="Name", class="input-text") }}
            </div>
            <div class="input-container">
                {{ form.author.label() }}:
                {{ form.author(placeholder="Author", class="input-text") }}
            </div>
            <div class="input-container">
                {{ form.price.label() }}:
                {{ form.price(placeholder="Price", class="input-number", type="number") }}
                VND
            </div>
            <div class="input-container">
                {{ form.quantity.label() }}:
                {{ form.quantity(placeholder="Quantity", class="input-number", type="number") }}
            </div>
            <div class="input-container">
                {{ form.category.label() }}:
                {{ form.category(class="input-text") }}
            </div>
            <div>
                <h3>{{ form.description.label() }}</h3>
                <textarea name="description" id="description" cols="30" rows="10"></textarea>
            </div>
        </section>
    
        <section id="confirm">
            <button class="button">
                <a href="{{ url_for('products.your_product') }}" class="link">Discard</a>
            </button>
            <button class="button" type="submit">
                {{ form.submit(class='input-submit') }}
            </button>
        </section>
    </form>
{% endblock %}

app/templates/products/product_details.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/products/product_details.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <section id="base-info">
        <div class="row">
            <div class="col-auto">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for i in range(pictures|length) %}
                            {% if i == 0 %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}" class="active"></li>
                            {% else %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}"></li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for picture in pictures %}
                            {% if picture == pictures[0] %}
                                <div class="carousel-item active">
                                    <img class="d-block product-image" src="{{ [image_service_url, picture.img_id]|join('') }}" alt="Product picture">
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                    <img class="d-block product-image" src="{{ [image_service_url, picture.img_id]|join('') }}" alt="Product picture">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col">
                <h2>{{ product.name }}</h2>
                <h5>by: {{ product.author }}</h5>
                <p>Price: {{ "{:,}".format((product.price * 1000)|int) }}</p>
                <p>Quantity: {{ product.quantity }}</p>
                <p>Category: {{ product.get_category().name }}</p>
            </div>
        </div>
    </section>
    <hr>
    <section id="description">
        <h2>Description</h2>
        <div class="row">
            <div class="col">
                {{ product.description }}
            </div>
        </div>
    </section>
    <hr>
    <section id="review">
        <h2>Review</h2>
        {% for review in reviews %}
            <div class="review-block mt-3 ml-3">
                <div class="row">
                    <img class="thumbnail" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" alt="profile image">
                    <h4 class="col-1">{{ review[1].username }}</h4>
                </div>
                <div class="row">
                    {% for i in range(review[0].star) %}
                        <span><i class="fas fa-star"></i></span>
                    {% endfor %}
                    {% for i in range(5 - review[0].star) %}
                        <span><i class="far fa-star"></i></span>
                    {% endfor %}
                    <p class="ml-2"><strong>{{ review[0].overview }}</strong></p>
                </div>
                {% if review[0].started_reading and review[0].finished_reading.date() %}
                    <div class="row">
                        <p>Started at {{ review[0].started_reading.date() }} - Finished at {{ review[0].finished_reading.date() }}</p>
                    </div>
                {% endif %}
                <div class="row">
                    <p>{{ review[0].content }}</p>
                </div>
            </div>
        {% endfor %}
    </section>

    <section id="edit">
        <!-- Button trigger modal -->
        <button type="button" class="button" data-toggle="modal" data-target="#deleteModal">
            <div class="link">Delete</div>
        </button>
        <!-- <button class="button">
            <a href="{{ url_for('products.your_product_delete', id=product.id) }}" class="link">Delete</a>
        </button> -->
        <button class="button">
            <a href="{{ url_for('products.your_product_edit', id=product.id) }}" class="link">Edit</a>
        </button>
    </section>

    <section id="modal">
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Do you really want to delete: {{ product.name }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="button" data-dismiss="modal">
                            <div class="link">Close</div>
                        </button>
                        <button type="button" class="button">
                            <a href="{{ url_for('products.your_product_delete', id=product.id) }}" class="link">Delete</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/products/products.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/products/products.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="search-form col-11">
                <form action="{{ url_for('products.search_products') }}" class="" method="POST">
                    {{ form.hidden_tag() }}
                    <input class="form-control mr-sm-2 input-searchbar" name="search" type="search" placeholder="Search for a book!" aria-label="Search">
                </form>
            </div>
    
            <div class="create-product col-1">
                <button class="create-button">
                    <a href="{{ url_for('products.your_product_new') }}" class="create-link"><i class="fas fa-plus"></i></a>
                </button>
            </div>
        </div>
    
        <div class="row">
            <div class="col">
                <div class="row">
                    {% for product in products.items %}
                        <div class="col-12 col-md-6 col-lg-4">
                            <div class="card">
                                {% if pictures[loop.index0] != -1 %}
                                    <img class="card-img-top product-image" src="{{ [image_service_url, product.pictures[0].img_id]|join('') }}" alt="Card image cap">
                                {% else %}
                                    <img class="card-img-top product-image" src="https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg" alt="Card image cap">
                                {% endif %}
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{{ url_for('products.your_product_details', id=product.id) }}" title="View Product">{{ product.name }}</a>
                                    </h4>
                                    <p class="card-text">
                                        {% if product.quantity == 0 %}
                                            <p class="out-of-stock-label">OUT OF STOCK</p>
                                        {% else %}
                                            {{ "{:,}".format((product.price * 1000)|int) }} đ
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
                    <br>

                    <div class="col-12">
                        <nav aria-label="...">
                            <ul class="pagination">
                                {% if prev_url %}
                                    <li class="page-item">
                                        <a class="page-link" href="{{ prev_url }}">Previous</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="{{ prev_url }}">Previous</a>
                                    </li>
                                {% endif %}

                                {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                                    {% if page_num %}
                                        {% if products.page == page_num %}
                                            <li class="page-item active">
                                                <a class="page-link" href="{{ url_for('products.your_product', page=page_num) }}">{{ page_num }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a class="page-link" href="{{ url_for('products.your_product', page=page_num) }}">{{ page_num }}</a>
                                            </li>
                                        {% endif %}
                                    {% else %}
                                        ...
                                    {% endif %}
                                {% endfor %}

                                {% if next_url %}
                                    <li class="page-item">
                                        <a class="page-link" href="{{ next_url }}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="{{ next_url }}">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/products/search_products.html
{% extends 'main/base.html' %}

{% block css_styles %}
    <link href="{{ url_for('static', filename='css/products/products.css') }}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col">
                <div class="row">
                    {% for product in products.items %}
                        <div class="col-12 col-md-6 col-lg-4">
                            <div class="card">
                                {% if pictures[loop.index0] != -1 %}
                                    <img class="card-img-top product-image" src="{{ [image_service_url, product.pictures[0].img_id]|join('') }}" alt="Card image cap">
                                {% else %}
                                    <img class="card-img-top product-image" src="https://www.publicdomainpictures.net/pictures/280000/velka/not-found-image-15383864787lu.jpg" alt="Card image cap">
                                {% endif %}
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{{ url_for('products.your_product_details', id=product.id) }}" title="View Product">{{ product.name }}</a>
                                    </h4>
                                    <p class="card-text">
                                        {{ "{:,}".format((product.price * 1000)|int) }} đ
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
                    <br>

                    <div class="col-12">
                        <nav aria-label="...">
                            <ul class="pagination">
                                {% if prev_url %}
                                    <li class="page-item">
                                        <a class="page-link" href="{{ prev_url }}">Previous</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="{{ prev_url }}">Previous</a>
                                    </li>
                                {% endif %}

                                {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                                    {% if page_num %}
                                        {% if products.page == page_num %}
                                            <li class="page-item active">
                                                <a class="page-link" href="{{ url_for('products.your_product', page=page_num) }}">{{ page_num }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a class="page-link" href="{{ url_for('products.your_product', page=page_num) }}">{{ page_num }}</a>
                                            </li>
                                        {% endif %}
                                    {% else %}
                                        ...
                                    {% endif %}
                                {% endfor %}

                                {% if next_url %}
                                    <li class="page-item">
                                        <a class="page-link" href="{{ next_url }}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="{{ next_url }}">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}